### ISSUE TITLE
not available for 0.155.2

### ISSUE THREAD

**Issue by Yonny24** [Deejayfool/hass-shutter-card#23]
Hi. This has been an awesome integration!.

Upgraded to 0.115.2 HA core and now see:

`Custom element doesn't exist: shutter-card.
entities:
  - buttons_position: left
    entity: cover.living_room_cover
    name: Living Room
    title_position: bottom
title: Living Blind
type: 'custom:shutter-card'`

Is this an incompatibility issue?
Appreciate any help.

**Comment by Deejayfool** [comment]
Hello,
I just updated HA to 0.115.2 today and the Shutter card is still working correctly. Try to reinstall the card and double check you correctly have a reference to "/hacsfiles/hass-shutter-card/hass-shutter-card.js" in Ressources.

**Comment by Deejayfool** [comment]
No answer since 1 week. I close this issue.
