### ISSUE TITLE
Request Offset

### ISSUE THREAD

**Issue by Pirol62** [Deejayfool/hass-shutter-card#24]
Hi,

my window is half open, when the UI is set to 66%.
Is it possible to set an offset option, so that the ui fits to the real cover position?

**Comment by MaxWinterstein** [comment]
I created some Pull Request https://github.com/Deejayfool/hass-shutter-card/pull/27 which seems to be based on the same intention.

**Comment by Deejayfool** [comment]
Feature added with Pull Request #69
