### ISSUE TITLE
No percentage

### ISSUE THREAD

**Issue by bussio** [Deejayfool/hass-shutter-card#28]
Today a new firmware 1.8.16 was released for the HmIP-BROLL. 
Since then the shutter card does not show any percentage of the shutter.

![2020-10-30_13-03-09](https://user-images.githubusercontent.com/48105172/97703149-6d954f00-1ab0-11eb-83b2-acdbce5a9452.jpg)

![2020-10-30_13-05-39](https://user-images.githubusercontent.com/48105172/97703982-dcbf7300-1ab1-11eb-99f9-d0b9b027078d.jpg)

**Comment by Deejayfool** [comment]
If you've a problem since you updated something else than the shutter card, it's 99% sure it has nothing to do with shutter card.
Look at your HmIP-BROLL if it correctly brings percentage to Home Assistant, it could be a good way to start.

**Comment by bussio** [comment]
Excuse me, a one-time lowering and raising of the shutter has solved the problem. 
Thanks for your effort!
