### ISSUE TITLE
Shutter doesn't scale 

### ISSUE THREAD

**Issue by Kaibob2** [Deejayfool/hass-shutter-card#3]
Hi,
great card so far. I was looking for something like this for some time. But is it possible, that the shutter image will scale to fit the size of a horizontal stack in mobile view. 
It looks okay on a desktop PC but the same card looks terrible on my mobile 
![Screenshot_20200623-155013_Samsung Internet](https://user-images.githubusercontent.com/20832276/85445642-e3822a80-b593-11ea-92cf-dad5842770b6.jpg)
This is a combined vertical / horizontal stack. 
Maybe you can fix this, if not I will use the card anyway but without stacking. 
Kai

**Comment by Deejayfool** [comment]
Hello,
I answered to this problematic in an other issue : https://github.com/Deejayfool/hass-shutter-card/issues/1#issuecomment-647696588

I won't be able to display it correctly in an horizontal stack because it can get very small then, and the shutter wouldn't be usable with your fingers.
