### ISSUE TITLE
Adding support for venetian blinds

### ISSUE THREAD

**Issue by zerev666** [Deejayfool/hass-shutter-card#32]
Hello that's the best custom card what I used in my life :)>

I just wondering if is any chance (in the future) to add support for venetian blinds? 
Just extra option for tilt position.

Cheers Lucas.

**Comment by cabe1214** [comment]
Just some thoughts here (as I also have some of these at home):
1. The blinds will have two default tilt positions. One when going up and another when going down. 
2. When the blinds are going down, the upper side of the blades is facing outside (we could say: -90º minimum tilt)
3a. When the blinds are going up, the upper side of the blades is facing the room (we could say: +90º maximum tilt)
3b. There are blinds that, when going up, the blades remain horizontal, (we could say the tilt is 0º). This means the maximum upwards tilt is not +90º but 0º.

Now some expectations (Requirements?):
1. The user shall be able to choose between (at least?) 6 tilt options (+90, +45, 0, -45, -90, none).
2. If a tilt different than "none" is specified, the corresponding tilt shall be applied after setting the blinds to the correct possition (0% closed, 100% open).

And eventually some implementation hints (sorry for not being able to collaborate here):
If the user blinds are behaving as in 3a or as in 3b will have to be defined manually by the user.
The time needed for changing between minimum tilt to maximum tilt will have to be defined manually. Depending on the delay between HA and the actuator you could specify more tilt options (+90,+60,+45,+30,0,etc.), at the end it is just going up/down for some miliseconds. 

@Deejayfool I hope what I wrote is understandable but in case it was not feel free to reach out for questions. I'll be happy to do some alpha/beta testing as well.

**Comment by Deejayfool** [comment]
Feature added with Pull Request #69
