### ISSUE TITLE
Covers without position percentage available display undefined

### ISSUE THREAD

**Issue by amaximus** [Deejayfool/hass-shutter-card#35]
Hi,

thanks for this card. One issue though:

for example a cover defined as a template and not providing position value displays undefined for position.
A configuration parameter for hiding the position would be welcomed.

```
platform: template
covers:
  reluxa:
    friendly_name: "Living shutter"
    value_template: >-
      {% if states('input_boolean.reluxa_open') == "on" %}
        open
      {% else %}
        closed
      {% endif %}
    open_cover:
      service: script.reluxa_open
    close_cover:
      service: script.reluxa_close
    stop_cover:
      service: script.reluxa_stop
    icon_template: >-
      {%- if  is_state('input_boolean.reluxa_open', 'on') -%}
      mdi:border-all-variant
      {%- else -%}
      mdi:view-headline
      {% endif %}
```
![shutter-card](https://user-images.githubusercontent.com/2511168/103641431-084b5780-4f52-11eb-928f-65f50b24700d.png)

**Comment by Deejayfool** [comment]
Hello,
This card is useless if your cover don't provide position. The meaning of this card is to manage the position of the cover.

**Comment by amaximus** [comment]
Hello, you're right, just tested it on my covers. However this would be worth mentioning in the README. Or as a feature request in such cases adding an entity that would reflect the open/close status of the cover would also make the card usable for such covers.

**Comment by Deejayfool** [comment]
I thought the GIF was enough self explaining to understand that it's to manage the position of the cover.
Anyway I don't plan to manage just an open/close status, because we can do this already in HomeAssistant with only an icon depending on the status of the cover.
Sorry that this card can't fit your needs.
