### ISSUE TITLE
KNX Shutter without position

### ISSUE THREAD

**Issue by msth** [Deejayfool/hass-shutter-card#39]
Hello, thank you for the great roller blind visualization. Unfortunately, the position is not displayed for me.

The KNX roller blind has the following values

```
- name: "Büro Hof"
  move_long_address: '3/1/37'
  move_short_address: '3/1/39'
  position_address: '3/1/38'
  position_state_address: '13/1/38'
  travelling_time_down: 15
  travelling_time_up: 16
```

![image](https://user-images.githubusercontent.com/1927680/107144087-0c93d780-6939-11eb-89e1-73224caefc2b.png)

it looks like the position data are given. But unfortunately this does not appear in the picture.

![image](https://user-images.githubusercontent.com/1927680/107144136-58468100-6939-11eb-8248-7ae69ee8f1ab.png)

what am I doing wrong

**Comment by Deejayfool** [comment]
Hello, if your cover correctly send the attribute "current_position" (and it seems to be the case), you should see the position instead of "unknown".
Can you send here the yaml configuration you use for the shutter card ?

**Comment by msth** [comment]
Hi, thanks for your repley. And yes, the cover sends the attribute "current_position".

This is the configuration :

```
type: 'custom:shutter-card'
entities:
  - entity: cover.Buro_Hof
    name: Richtung Hof
    buttons_position: right
```

**Comment by Deejayfool** [comment]
It seems that your entity should normally be called "cover.buro_hof" (without uppercase). Can you try with it in lowercase ?

**Comment by msth** [comment]
OK, thanks. there you can see that I'm new to home-assistant.
