### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by pergolafabio** [Deejayfool/hass-shutter-card#4]
Hi,

i have template covers, so only up/down/stop command ... no percentage ..

i have implemented this card now, the card shows, but i always see "undefined" , also the up/down arrow doesnt work
the word "undefined" is where the 0 .. 100% should be

**Comment by Deejayfool** [comment]
Hello,
Of course if you don't have any percentage, you won't be able to use this card. The shutter picture can only be calculated based on a percentage.

**Comment by pergolafabio** [comment]
Oh , that's too bad, not possible to use it with up/down only ? I love the picture card itself

**Comment by Deejayfool** [comment]
I don't plan to do that thing, sorry :/ . The main objective of this card is to use the shutter picture to define a specific percentage.

**Comment by pergolafabio** [comment]
Ok, no problem, thnx for feedback
