### ISSUE TITLE
Invert open/close

### ISSUE THREAD

**Issue by jurgen272** [Deejayfool/hass-shutter-card#5]
Hi, I have some covers and when they are open the card shows a closed shutter.
So if it's possible to invert this with an option in the card thois would be great

**Comment by Deejayfool** [comment]
Hello @jurgen272 ,
I just updated the card for your request. You can now use a setting "invert_percentage" to fit your needs :) .
Tell me if it works correctly so I can close this issue.

**Comment by jurgen272** [comment]
Hi,
The card is ok now.
Thank you very much
J

Deejayfool <notifications@github.com> schreef op 27 juni 2020 12:21:24 CEST:
