### ISSUE TITLE
bad indentation of a sequence entry

### ISSUE THREAD

**Issue by pocahozas** [Deejayfool/hass-shutter-card#52]
Hello everybody

Does anyone know why I get this error?

Errores de configuración detectados:
bad indentation of a sequence entry (5:9)

![error](https://user-images.githubusercontent.com/78036897/130691922-b0ff93cd-c562-4279-b6b4-37b6b68ffb6c.jpg)

 2 | title: Persianas
 3 | entities:
 4 |   - cover.shellyswitch25_d8bfc01a522f
 5 |     name: Left shutter
-------------^
 6 |     buttons_position: left
 7 |     title_position: bottom

Thanks a lot

**Comment by Deejayfool** [comment]
Hello,
If you want to add parameters (like name, buttons_position, etc...), you need to prefix the entity with "entity:" like in the example :

![image](https://user-images.githubusercontent.com/708628/130733703-4736b8d5-96b7-452f-9ecd-8921a0a626b2.png)
