### ISSUE TITLE
Issue: Blind not centered

### ISSUE THREAD

**Issue by simone7121** [Deejayfool/hass-shutter-card#54]
When I insert the Custom: blind-card into a Custom: vertical-stack-in-card, the curtain is automatically decentralized on the card interface. I tried to solve it by using a built-in style and putting a custom css in it, but it doesn't override it.

>This is the code

	- type: custom:blind-card
	    entities:
	      - entity: cover.tradfri_blind
	        name: Tenda Studio
	        buttons_position: right
	        title_position: top
	        blind_color: '#636160'
	

> And i've added this piece of custom CSS.

    style: |
	      .sc-blind-middle {
	        margin: auto;
	      }

> But nothing happens.

![Immagine 2021-09-13 092038](https://user-images.githubusercontent.com/31928695/133040815-a7bde72e-cdd6-42de-865f-c6ff3eb355f8.png)

**Comment by Deejayfool** [comment]
Hello,
"blind-card" is not my card. My card is called "shutter-card".
