### ISSUE TITLE
Second blind card does not get updated.

### ISSUE THREAD

**Issue by deam0n** [Deejayfool/hass-shutter-card#55]
Hi!

I've 2 Ikea FYRTUR blinds. With blind 1 the shutter card works as expected, but with the blind 2, the position and card animation / update does not happen. The buttons successfully control the blind and clicking on the card also but the position percentage and shutter image are stuck at 94% every time.

The entity HA card, successfully gets the position of the blind 2.

**Comment by nutsofamily** [comment]
I have same issue but not with Ikea blinds. Tuya motors. The buttons work up/down /stop but no animation

**Comment by deam0n** [comment]
issue gone after o repaired the blind.
