### ISSUE TITLE
Request: buttons_position (add top/bottom)

### ISSUE THREAD

**Issue by txespirito** [Deejayfool/hass-shutter-card#56]
Its possible to add the options top and botton to the button_possition? It is interresting to fit 2 next to each other in a horizontal stack. Especially on mobile, to save screen estate.

**Comment by markblokpoel** [comment]
You can try using card-mod to customize the layout of the shutter card. This worked for me:


```
type: custom:shutter-card
entities:
  - entity: cover.bedroom_3_blinds
    name: Bedroom 3
card_mod:
  style: |
    ha-card .sc-shutter-middle {
      width: 100%;
      flex-direction: column-reverse !important;
    }
    ha-card .sc-shutter-button + br {
      display: none;
    }
```

**Comment by tenkaibr** [comment]
I would like that too.

**Comment by qvqn** [comment]
would also like cleaner option than card mod

**Comment by Deejayfool** [comment]
Feature added with Pull Request #69
