### ISSUE TITLE
Buttons not visible in Card

### ISSUE THREAD

**Issue by miit86** [Deejayfool/hass-shutter-card#57]
Hi,

Using HA Beta.
UP/DOWN/STOP buttons not visible anymore.

**Comment by guevara777** [comment]
same problem here. is there a workaroud for that?

**Comment by miit86** [comment]
@guevara777 
You can use my repo to fix the buttons.

Looks like this repo isn't maintained anymore.

**Comment by guevara777** [comment]
Thank you. I tried to do it, but i think i'm doing it wrong.

i changed the file hass-shutter-card.js in the www/community/hass-shutter-card - folder in lines 55, 56 and 57 from

`<ha-icon-button icon="mdi:arrow-up" class="sc-shutter-button" data-command="up"></ha-icon-button>`
`<ha-icon-button icon="mdi:stop" class="sc-shutter-button" data-command="stop"></ha-icon-button>`
`<ha-icon-button icon="mdi:arrow-down" class="sc-shutter-button" data-command="down"></ha-icon-button>`

to

`<ha-icon-button class="sc-shutter-button" data-command="up"><ha-icon icon="mdi:arrow-up"></ha-icon></ha-icon-button>`
`<ha-icon-button class="sc-shutter-button" data-command="stop"><ha-icon icon="mdi:stop"></ha-icon></ha-icon-button>`
`<ha-icon-button class="sc-shutter-button" data-command="down"><ha-icon icon="mdi:arrow-down"></ha-icon></ha-icon-button>`

and then restarted home assistant. 

Sadly the buttons are still missing. May you tell me how i can do it?

**Comment by Deejayfool** [comment]
Don't worry, this repo is not dead :). I still use it personally so if it doesn't work anymore with the new version of Home Assistant, I'll update it. But as I don't use Beta version, it's complicated for me to test it. I will fix it as soon as Home Assistant release the new version.

**Comment by miit86** [comment]
Hi,

Just merge my PR. And the problem is fixed.

**Comment by Deejayfool** [comment]
I just released v1.3.0 which fixes this bug.
