### ISSUE TITLE
Offset for calibration of middle point

### ISSUE THREAD

**Issue by joaopequeno-git** [Deejayfool/hass-shutter-card#60]
Hi,

When we use Shelly devices, they dont take in consideration the roller blinds holes that take some time to close.
By this the real middle point after roller calibration is 66% and not 50%.
This means we should have a calibration of middle point.

If you enter a position in %, e.g. 66%, the shutter position 66% will be interpreted as 50%, so it will be read as 50% and if you set 50% it will go to 66%. So 50-100% values will be crushed to 66-100% values and 0 - 50% values will be expanded to 0 - 66%. This way the shutter will be half way down on reading or setting 50%. Right now I have to set 66%, because it takes the motor longer to go to the end position.

Can you help?

**Comment by Deejayfool** [comment]
Feature added with Pull Request #69
