### ISSUE TITLE
up/stop/down icons are broken on android

### ISSUE THREAD

**Issue by foormea** [Deejayfool/hass-shutter-card#61]
Hi, I have seen that recently there was some issues with icons. The icons were broken on web for a bit following HA's update, but the issue was solved with shutter-card's later update. Great, many thanks!
I've just noticed that the icons are broken on Android: there's just no icon on the buttons, the buttons are invisible.

Please let me know if there is anything I can do to help. Thank you.

Android's Home Assistant app version: 2021.10.0-full
Home Assistant version: 2021.11.1
Shutter card 1.3.0

**Comment by Deejayfool** [comment]
Hello, I got the same problem on the Android app.
It's just a problem with cache. I don't know how cache is managed by the Android app, but what I did is just clear cache and wipe data of the app from my smartphone settings. Then I logged in again on the app and everything was good :).

**Comment by foormea** [comment]
Thanks for your response. Indeed, clearing cache just fixed it. Apologies, I should have tried that before reaching out.
