### ISSUE TITLE
Hide Name and title

### ISSUE THREAD

**Issue by manustars** [Deejayfool/hass-shutter-card#63]
hi, its possible hide the the name and title? 
this my code:
`type: vertical-stack
cards:
  - type: 'custom:button-card'
    name: TAPPARELLA CUCINA
    template: label_center
  - type: horizontal-stack
    cards:
      - type: 'custom:shutter-card'
        title: Aperta al
        show_name: false
        show_title: false
        entities:
          - entity: cover.tapparella_cucina_2
            name: Aperta al
            button_position: left
            title_position: bottom
`
and this the result:

![image](https://user-images.githubusercontent.com/60410607/146003738-21f74cd5-00fc-4a02-bc41-0a7515a48ec9.png)

**Comment by Deejayfool** [comment]
Hello, for the shutter-card, just don't set the "title" property in your yaml as explained in the documentation.
For the button-card, I can't help you because I didn't develop this card.
