### ISSUE TITLE
Cover is showing double?

### ISSUE THREAD

**Issue by mm3103mm** [Deejayfool/hass-shutter-card#66]
Hello everybody,

I hope you can help me. I have 2x Shelly 2.5 for controlling my shutters. Now i wanted to use this shutter card and its showing everything double:

![shutter](https://user-images.githubusercontent.com/78447737/147878857-7798441a-4dbc-45e4-81dc-1baec5897903.png)

How can I solve that?

Best regards
Michael

**Comment by Deejayfool** [comment]
This is not an issue. You added your rollers 2 times. I think you should take time to look at how YAML is working.

**Comment by mm3103mm** [comment]
Hi thanks for answering. Actually i just added the rollers only one time in shelly integration. I dont know where to search else. I did not add anything manually regarding the rollers in any yaml files. I thought that it has something to do that the shelly 2.5 can be also used as 2 relais or the roller shutter function. If I am only adding them in a grid its also only shown as one device like in the picture below. Can you maybe help me a bit?

![shutter2](https://user-images.githubusercontent.com/78447737/147884793-dba1ffce-2024-4557-b742-6902e3d2d7b2.png)
