### ISSUE TITLE
Down Button not available when Shutter is open

### ISSUE THREAD

**Issue by Kenny-BC** [Deejayfool/hass-shutter-card#78]
Hi Guys,
ive the latest HomeAssistant Version installed and at the moment are the shutters closed. 
When you see my Screenshot you see that the open button is not available. Same when the shutters are open, then the close button is not available.

![Shutter](https://user-images.githubusercontent.com/77678216/203639921-a694b103-1bf0-4d6d-a087-71f9d9fc66d1.JPG)

Can you tell me whats wrong?

**Comment by Deejayfool** [comment]
Hello,
I think you're on the wrong repo. This is not the Shutter card.
